[System]
InitializeForm=·ÂÕæÆ÷Emulator1
IsCanRunMultiple=0
IsAutoConnectWifi=0
DeviceNo=IN4301000230
OffLineStartTime=XY1M87KWQn5oAKOgqBi8XOS4e1p20mBv
OffLineEndTime=XY1M87KWQn5joyhvJxsux0MzRUcZEtTa
IsOfflineMode=1
